# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
!pip install mdutils

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np
answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
hint(2)

# The version nummber
print(np.__version__)

# The exact configs
np.show_config()

answer(2)

hint: np.__version__, np.show_config)
1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: D:/Program Files/anaconda3/Library/include
    lib directory: D:/Program Files/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    fam

#### 3. Create a null vector of size 10 (★☆☆)

In [12]:
hint(3)

Z = np.zeros(10)
print(Z)

answer(3)

hint: np.zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [17]:
hint(4)

print("%d bytes" % (Z.size * Z.itemsize))

# using f-string
print(f"{Z.size * Z.itemsize} bytes")

answer(4)

hint: size, itemsize
80 bytes
80 bytes
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [23]:
hint(5)

print(np.info(np.add))

answer(5)

hint: np.info
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the def

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
hint(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)

answer(6)

hint: array[4]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [30]:
hint(7)

# Without .reshape() is only one-dimensional 
Z = np.arange(10,50)
print(Z)

answer(7)

hint: arange
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [33]:
hint(8)

Z_r = Z[::-1]
print(Z_r)

answer(8)

hint: array[::-1]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [36]:
hint(9)

Z = np.arange(9).reshape(3,3)
print(Z)

answer(9)

hint: reshape
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [4]:
hint(10)

Z = [1,2,0,0,4,0]
Z_n = np.nonzero(Z)[0]
print(Z_n)

answer(10)

hint: np.nonzero
[0 1 4]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [4]:
hint(11)

Z = np.eye(3)
print(Z)

answer(11)

hint: np.eye
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [9]:
hint(12)

Z = np.random.random((3,3,3))
print(Z)

answer(12)

hint: np.random.random
[[[0.99105399 0.69207554 0.67309643]
  [0.69786707 0.66728229 0.20399257]
  [0.02889637 0.703043   0.30631686]]

 [[0.12539766 0.50160258 0.13455505]
  [0.17520154 0.06742788 0.87297267]
  [0.52495016 0.09177376 0.95135417]]

 [[0.13069924 0.04572971 0.02622312]
  [0.89805229 0.36203633 0.87694929]
  [0.8203635  0.85563891 0.60527123]]]
Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
hint(13)

Z = np.random.random((10,10))
print(np.min(Z))
print(np.max(Z))

Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

answer(13)

hint: min, max
0.00775349907719447
0.9998318125228428
0.00775349907719447 0.9998318125228428
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
Z = np.random.random(30)
print(Z.mean())

answer(14)

0.40875969262551437
Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [9]:
hint(15)

Z = np.ones((10,10))
Z1 = np.ones((10,10))
Z2 = np.ones((10,10))

# only set the first and last column to be 1
Z1[:,1:-1] = 0
print(Z1)

# only set the first and last row to be 1
Z2[[2,4],:] = 0
print(Z2)

# set both the first and last column and row to be 1
Z[1:-1,1:-1] = 0
print(Z)

answer(15)

hint: array[1:-1, 1:-1]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [10]:
hint(16)

# pad: add dimensions
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=5)
print(Z)

# indexing: does not change the dimension
Y = np.ones((5,5))
Y[:,[0, -1]] = 0
Y[[0, -1],:] = 0
print(Y)

answer(16)

hint: np.pad
[[5. 5. 5. 5. 5. 5. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 5.]
 [5. 5. 5. 5. 5. 5. 5.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [45]:
hint(17)

# nan
# False
# False
# nan
# True
# False

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
print(np.isclose(0.3, 3 * 0.1)) # True
print(np.inf * 0) # nan

answer(17)

hint: NaN = not a number, inf = infinity
nan
False
False
nan
True
False
True
nan
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [12]:
hint(18)

# -1: just below the diagonal
Z = np.diag(1+np.arange(4),k=1)
print(Z)

answer(18)

hint: np.diag
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]
Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [16]:
hint(19)

Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2, 1::2] = 1
print(Z)

answer(19)

hint: array[::2]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [18]:
hint(20)

print(np.unravel_index(99, (6,7,8)))

answer(20)

hint: np.unravel_index
(1, 5, 3)
print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [30]:
hint(21)

Z = np.tile(np.array([[0,2],[1,0]]),(4,4))
print(Z)

answer(21)

hint: np.tile
[[0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]]
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [39]:
hint(22)

Z = np.random.random((5,5))
print(Z.mean())
print(np.mean(Z))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

answer(22)

hint: (x -mean)/std
0.5217646407001868
0.5217646407001868
[[-0.3752055   0.06196872 -1.20320752  1.63213224  0.90108644]
 [-0.89029587  0.14038982 -1.29001951 -1.02270159  0.56335394]
 [ 1.59585741  0.89528098 -1.49193903  1.15186956 -0.91479042]
 [-0.31962163 -1.35625971  0.69910701  1.12325751 -0.46898   ]
 [ 0.39939293 -1.32433672  1.29974598  0.73756234 -0.54364738]]
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [42]:
hint(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

colors = np.array([(255, 0, 0, 255),    # Red
                   (0, 255, 0, 255),    # Green  
                   (0, 0, 255, 255)],   # Blue
                  dtype=color)

pixel = np.array((255, 128, 0, 255), dtype=color)
print(pixel)

answer(23)

hint: np.dtype
(255, 128, 0, 255)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [46]:
hint(24)

#Z = np.matmul(np.ones((5,3)), np.ones((3,2)))
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

answer(24)

hint:
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [52]:
hint(25)

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

answer(25)

hint: >, <
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [58]:
# sum(iterable, start) second arg: start number
print(sum(range(5),-1)) #9

# The numpy sum function
from numpy import *
print(sum(range(5), 0))

answer(26)

10
10
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [71]:
import numpy as np

Z = np.array([1, 2, 3, 4, 5])
print(Z)

# [1^1, 2^2, 3^3, 4^4]
print(Z**Z)

# bit shifting
print(2 << Z >> 2)

# Comparison between Z and -Z
print(Z <- Z)

# Complex multiplication
print(1j*Z)

# Division
print(Z/2/2)

#print(Z<Z>)

[1 2 3 4 5]
[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[0.25 0.5  0.75 1.   1.25]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [76]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Lisa\AppData\Local\Temp\ipykernel_32636\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Lisa\AppData\Local\Temp\ipykernel_32636\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Lisa\AppData\Local\Temp\ipykernel_32636\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [79]:
answer(29)

# Uniform distribution
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))
[ 6.43133095  3.02801461  2.47636144  0.10499491 -1.92213681  6.85581437
  3.63100115 -3.62074411 -7.8762779  -1.53823598]
[ 7.  4.  3.  1. -2.  7.  4. -4. -8. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [83]:
answer(30)

# Random intergers
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
[1 7 4 2 3 9 6 4 6 5]
[2 6 9 3 8 4 2 0 2 7]
[2 3 4 6 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [84]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [87]:
print(np.sqrt(-1))

# Extended math mode
print(np.emath.sqrt(-1))

nan
1j


C:\Users\Lisa\AppData\Local\Temp\ipykernel_32636\3391261550.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [89]:
answer(33)
print(np.datetime64('today') - np.timedelta64(1))

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
2025-09-11


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [91]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [94]:
answer(35)
A = np.ones(3)*1
B = np.ones(3)*2
print(A)
print(B)

# Store the output on B
print(np.add(A,B,out=B))
print(B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[3. 3. 3.]


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [103]:
answer(36)
Z = np.random.uniform(-10,10,10)
print(Z)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

# Depneds on round up or down

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))
[-5.20420939 -4.86164242 -1.52618185  2.86641895  8.15387487  1.80387639
  7.59098862  7.8019753   4.54191769 -5.2592167 ]
[-6. -5. -2.  2.  8.  1.  7.  7.  4. -6.]
[-6. -5. -2.  2.  8.  1.  7.  7.  4. -6.]
[-6. -5. -2.  2.  8.  1.  7.  7.  4. -6.]
[-5 -4 -1  2  8  1  7  7  4 -5]
[-5. -4. -1.  2.  8.  1.  7.  7.  4. -5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [108]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [117]:
answer(38)

def generate():
    for i in range(10):
        yield i

lst = list(generate())
print(lst)

# iterable: the generator generate()
# count: how many items to read; -1 means read all items until the iterable is exhausted
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [122]:
answer(39)

# Defult endpoint value = True
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

# Generate random number (shape = arg) between [0,1)
Y = np.random.random(10)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [125]:
answer(40)

Z = np.random.random(10)
print(Z)
print(np.sort(Z))

Z = np.random.random(10)
Z.sort()
print(Z)
[0.97548171 0.32367292 0.22646252 0.1915421  0.06899381 0.25605884
 0.12574319 0.46172504 0.0841708  0.2324041 ]
[0.06899381 0.0841708  0.12574319 0.1915421  0.22646252 0.2324041
 0.25605884 0.32367292 0.46172504 0.97548171]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [132]:
answer(41)

Z = np.arange(10)
print(Z)
print(np.add.reduce(Z))
print(np.multiply.reduce(Z))

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)
[0 1 2 3 4 5 6 7 8 9]
45
0


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)